micronaut:
  application:
    name: productService
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/productdatabase
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: postgres
    password: 1234
netty:
  default:
    allocator:
      max-order: 3

jpa.default.properties.hibernate.hbm2ddl.auto: update

